on: push


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.0.0
    - name: Setup Go environment
      uses: actions/setup-go@v3.0.0
      with:
        go-version: 1.18
    - name: Run
      run: make test
